# Class for different message types
class MessageTypes:

    SEND_TO_ALL = "STA"
    CLIENT_LIST = "CLI"
    VC_PARTICIPANT = "VCP"
    HEARTBEAT = "HBT"
    JOIN_NETWORK_SERVER = "JNS"
    JOIN_NETWORK_CLIENT = "JNC"
    REPLICATION_CLIENT_LIST = "RCL"
    REPLICATION_SERVER_LIST = "RSL"
    REPLICATION_CHAT_HISTORY = "RCH"
    REPLICATION_CLIENT_CONN_LIST = "RCC"
    REPLICATION_SERVER_VC = "RSV"
